version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rebbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root

volumes:
  rabbitmq_data:
